development:
  dialect: postgres
  database: {{envOr "DATABASE" "bench"}}
  user: {{envOr "DB_USER" "brycolem"}}
  password: {{envOr "DB_PWD" "your_password"}}
  host: localhost
  port: 5432
  pool: 50
  sslmode: disable

production:
  dialect: postgres
  database: {{env "DATABASE"}}
  user: {{env "DB_USER"}}
  password: {{env "DB_PWD"}}
  host: localhost
  port: 5432
  pool: 50
  sslmode: require

